### ISSUE TITLE
PowerShell not showing as an option when right clicking on script

### ISSUE THREAD

**Issue by C-A-Hernandez** [PwC-IR/Office-365-Extractor#2]
Please note currently PowerShell is installed on the PC that the Office-365-Extractor was also installed on; however, when right clicking on the script of Office-365-Extractor "Run with PowerShell" is not showing as an option.  Please suggest how to address this issue... thank you...

**Comment by PwC-IR** [comment]
Hi, could you try to open Powershell and then run the script.

1. Press Start and search for Powershell
2. Go to the right directory (I.e cd C:\Users\test\Downloads\) 
3. Run the script. .\Office365_Extractor.ps1
