### ISSUE TITLE
Time interval infinite loop

### ISSUE THREAD

**Issue by trevlix** [PwC-IR/Office-365-Extractor#3]
If a time interval is not entered (ie just hitting enter at that prompt), the script will attempt to pull 0 seconds of logs which turns into an infinite loop of errors. Can a default value or re-prompt be added in for the time interval?

**Comment by PwC-IR** [comment]
Hi, thanks for your message. That is correct, since you can't pull logs for 0 seconds. We will add a default value / re-prompt in our next update. Thanks a lot for the feedback!

**Comment by PwC-IR** [comment]
Hi, I want to thank you again for your suggestion on improving the script. We added the option that if you press enter it will take a default input value of 60.
